# This is a basic workflow to help you get started with Actions
name: PHP CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-and-deploy:
    # The type of runner that the job will run on: ubuntu-latest
    runs-on: ubuntu-latest

    env:
      COMPOSER_VERSION: 2.1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      # with:
      #   persist-credentials: false

      - name: composer-php
        # You may pin to the exact commit or the version. only support on Linux
        # uses: nick-zh/composer@e4150fc9fc675948c55d3ef85282328bdd40a60e
        uses: nick-zh/composer@php7.3
        with:
          # Action to run, e.g. install, add any additional options you need also here
           action: install --prefer-dist --no-progress # optional, default is install

      - name: Validate composer.json and composer.lock
        run: |
          php -v
          composer --version
          composer validate --strict

      - name: Validate depends
        run: composer depends --tree --version --no-cache

      - name: remove no updated files
        run: |
          rm -rf vendor/
          rm -rf .git/
          rm -rf .github/

      - name: FTP to aliyun vh
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ALIYUN_VH_HOST }}
          username: ${{ secrets.ALIYUN_VH_USERNAME }}
          password: ${{ secrets.ALIYUN_VH_PASSWORD }}
          local-dir: ./
          server-dir: htdocs/booster/


        # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
        # Docs: https://getcomposer.org/doc/articles/scripts.md
        # - name: Run test suite
        #   run: composer run-script test

